services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: doc-server-prod
    networks:
      - doc-frontend-network
      - doc-backend-network
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"
